name: laundry_lens
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  modal_progress_hud_nsn: ^0.5.0
  provider: ^6.1.5+1
  firebase_messaging: ^16.0.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  timezone: ^0.10.1
  android_alarm_manager_plus: ^5.0.0
 # mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - assets/sounds/
  fonts:
     - family: Poppins
       fonts:
       - asset: fonts/Poppins-SemiBold.ttf
     - family: Momo
       fonts:
         - asset: fonts/MomoTrustDisplay-Regular.ttf

