name: laundry_lens
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2-5

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  modal_progress_hud_nsn: ^0.5.0
  provider: ^6.1.5+1
  firebase_messaging: ^16.0.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  android_alarm_manager_plus: ^5.0.0
  flutter_native_splash: ^2.4.7
  #google_sign_in: ^7.2.0
  google_sign_in: ^6.2.1
 # mobile_scanner: ^7.1.3
flutter_icons:
    android: true
    ios: true
    image_path: "images/laundry_lens_icon.png"
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - assets/sounds/
  fonts:
     - family: Poppins
       fonts:
       - asset: fonts/Poppins-SemiBold.ttf
     - family: Momo
       fonts:
         - asset: fonts/MomoTrustDisplay-Regular.ttf

flutter_native_splash:
  color: "#459380"   # mÃªme couleur que ton app
  image: images/LAUNDRY_LENS.png

  android: truen

  ios: true
  web: false

  android_gravity: center
  ios_content_mode: scaleAspectFit
